In [1]:
import pandas as pd

#Load "Recipes.Csv"

recipes = pd.read_csv(r"C:\Users\rahim\OneDrive\Desktop\Math_Thesis _ mechine\Recipes.csv")
defects = pd.read_csv(r"C:\Users\rahim\OneDrive\Desktop\Math_Thesis _ mechine\Defects.csv")

# get columns from Recipes.csv
heat_id = list(recipes['HEAT_ID'])
material_code = list(recipes['Material_Code'])
weight = list(recipes['WEIGHT'])

# get columns from Defects.csv
# get columns for HEAT_ID from defects.csv
heat_id_defect = list(defects['HEAT_ID'])         ##need to know how many time HEAT_ID used....
defect_type = list(defects['DEFECT_TYPE'])        ## need to know how many times DEFECT_TYPE used...

# result
result = []
# material code unique
material_code_unique = [] ## get unique for material_code

# remove duplicate
unique_heat_id = list(set(heat_id)) ## get unique for heat id
# heat_id vs mat code
material_code_set = {}  ## create dictionary with keys are HEAT_ID and values are Material_code
# heat_id vs weight following mat code
weight_set = {} ##I have create dictionary with keys are HEAT_ID and values are  WEIGHT

# heat_id vs defect
defect_set = {} ## create dictionary with keys are HEAT_ID and values are DEFECT_TYPE

In [2]:
# initialize dictionary 
for i in range(len(unique_heat_id)):
    material_code_set[unique_heat_id[i]] = []
    weight_set[unique_heat_id[i]] = []
    defect_set[unique_heat_id[i]] = []

# each unique heat_id has different material_code and weight
# and set key as heat_id and values as material_code and weight
for i in range(len(heat_id)):
    material_code_set[heat_id[i]].append(material_code[i])
    weight_set[heat_id[i]].append(weight[i])

# each unique heat_id has different defect type
for i in range(len(heat_id_defect)):
    try:
        defect_set[heat_id_defect[i]].append(defect_type[i])
    except:
        continue

# material unique
material_code_temp = []
# get keys from defect_set dictionary, keys are unique heat id...
defect_set_key = list(defect_set.keys())
# get all material code from material code set
for i in range(len(defect_set_key)):
    material_code_temp += material_code_set[defect_set_key[i]]
# get unique material code.
material_code_unique = list(set(material_code_temp))

In [3]:

# crate dataframe
defect_key_list = sorted(list(defect_set.keys()))
# loop for all defect key list
for i in range(len(defect_key_list)):
    # each values of defect dictionary is list, I have to get all values from defect dictionary
    for j in range(len(defect_set[defect_key_list[i]])):
        temp = []
        # heat id
        temp.append(defect_key_list[i])
        # all matmaterial
        for k in range(len(material_code_unique)):
            # if material unique code is in material code dictionary, value are weight of key of defect dictionary
            if material_code_unique[k] in material_code_set[defect_key_list[i]]:
                temp.append(weight_set[defect_key_list[i]][material_code_set[defect_key_list[i]].index(material_code_unique[k])])
            # if not, value will be 0.0
            else:
                temp.append(0.0)
        # M_sum
        temp.append(sum(weight_set[defect_key_list[i]]))
        # M_Mean
        temp.append(sum(weight_set[defect_key_list[i]]) / len(weight_set[defect_key_list[i]]))
        # M_num
        temp.append(len(weight_set[defect_key_list[i]]))
        # Repeat
        temp.append(len(defect_set[defect_key_list[i]]))
        # defect id
        temp.append(defect_set[defect_key_list[i]][j])
        result.append(temp)

columns = []
columns.append('HEAT_ID')
for i in range(len(material_code_unique)):
    columns.append('Mat_' + str(material_code_unique[i]))
columns.append('M_Sum')
columns.append('M_Mean')
columns.append('M_Num')
columns.append('Repeat')
columns.append('Defect_Id')

##Create csv file
df1 = pd.DataFrame(result, columns=columns)
#df1.to_csv(r"C:\Users\rahim\OneDrive\Desktop\Math_Thesis _ mechine\test.csv")

In [10]:
import pandas as pd

Final = pd.read_csv(r"C:\Users\rahim\OneDrive\Desktop\Math_Thesis _ mechine\test.csv")
df1 = Final 
                                                 ##print(df1)
                                                 ##df1.head(10)
#Remove Columns (0)       
Final_Datafram=df1.drop(df1.columns[0], axis = 1)
##Final_Datafram.head(10000)

#reverse the columns
reverse=Final_Datafram[Final_Datafram.columns[::-1]]
##reverse

##Remove duplicate data
removeDuplicate=reverse.drop_duplicates()
removeDuplicate

,Defect_Id,Repeat,M_Num,M_Mean,M_Sum,Mat_126,Mat_125,Mat_124,Mat_122,Mat_121,...,Mat_209,Mat_208,Mat_207,Mat_190,Mat_183,Mat_182,Mat_181,Mat_180,Mat_166,HEAT_ID
0,59,93,3,18665.333333,55996.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1701192
2,63,93,3,18665.333333,55996.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1701192
3,71,93,3,18665.333333,55996.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1701192
5,89,93,3,18665.333333,55996.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1701192
11,90,93,3,18665.333333,55996.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1701192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510944,147,143,9,16908.933333,152180.4,10890.3,0.0,4731.0,0.0,21178.3,...,0.0,0.0,0.0,0.0,0.0,0.0,10033.0,0.0,0.0,1811206
510956,212,143,9,16908.933333,152180.4,10890.3,0.0,4731.0,0.0,21178.3,...,0.0,0.0,0.0,0.0,0.0,0.0,10033.0,0.0,0.0,1811206
510957,193,143,9,16908.933333,152180.4,10890.3,0.0,4731.0,0.0,21178.3,...,0.0,0.0,0.0,0.0,0.0,0.0,10033.0,0.0,0.0,1811206
510959,55,143,9,16908.933333,152180.4,10890.3,0.0,4731.0,0.0,21178.3,...,0.0,0.0,0.0,0.0,0.0,0.0,10033.0,0.0,0.0,1811206
510960,216,143,9,16908.933333,152180.4,10890.3,0.0,4731.0,0.0,21178.3,...,0.0,0.0,0.0,0.0,0.0,0.0,10033.0,0.0,0.0,1811206